export default {
	Residential: {
		Flat: true,
		"House/Villa": false,
	},
	Commercial: {
		"Office Space": false,
		"Shop/Showroom": false,
		"Commercial Land": false,
		"Coworking Space": false,
		"Warehouse/Godown": false,
		"Industrial Building": false,
		"Industrial Shed": false,
	},
	Others: { "Agriculture Land": false, "Farm House": false },
	"Raj Nagar Extension": true,
	Indirapuram: false,
	"Crossings Republik": false,
	Vasundhara: false,
	"NH 24": false,
	Vaishali: false,
	"5 Lac": true,
	"10 Lac": false,
	"15 Lac": false,
	">15 Lac": false,
	"1 BHK": true,
	"2 BHK": false,
	"3 BHK": false,
	"4 BHK": false,
	"5 BHK": false,
	">5 BHK": false,
	Construction: { "Ready to move": false, "Under Construction": false },
	Ownership: { "Ready to move": false, "Under Construction": false },
	Sale: { "Ready to move": false, "Under Construction": false },
	Covered: { "Ready to move": false, "Under Construction": false },
	Bathroom: { "Ready to move": false, "Under Construction": false },
	Furnishing: { "Ready to move": false, "Under Construction": false },
	Facing: { "Ready to move": false, "Under Construction": false },
	Floor: { "Ready to move": false, "Under Construction": false },
	Amenities: { "Ready to move": false, "Under Construction": false },
};
